# Generated by Django 4.1.4 on 2022-12-29 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Phone_no', models.IntegerField()),
                ('Address', models.CharField(max_length=100)),
                ('Age', models.IntegerField()),
                ('date', models.DateField()),
                ('username', models.CharField(max_length=100)),
            ],
        ),
    ]
