# Generated by Django 4.1 on 2022-08-15 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_entry',
            name='Phone_no',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student_entry',
            name='Reg_no',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
